spring.application.name=todolist
spring .datasource.url=jdbc:mysql://localhost:1521/TSKM26
spring.databasource.username=TSKM26
spring.databasource.password=TSKM26
spring.databasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true