spring.application.name=todolist

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=TSKM26
spring.datasource.password=TSKM26
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
server.port=8081
